#!/usr/bin/env python3

import json
import os
from pathlib import Path


def main():
    directory = Path(__file__).absolute().parent.parent
    languages = sorted(x.name for x in directory.iterdir()
                       if x.is_dir() and len(x.name) == 2 and x.name != 'en')

    if 'GITHUB_ACTION' in os.environ:
        print(f'::set-output name=languages::{json.dumps(languages[:2])}')
    for language in languages[:2]:
        print(language)


if __name__ == '__main__':
    main()
